/**
 * Cloudflare Turnstile Verification Module (Story 2.5B)
 *
 * Provides bot protection through Cloudflare Turnstile challenge-based verification.
 * Implements fail-open pattern for reliability (allow submission if API unreachable).
 *
 * Related:
 * - ADR-013: Cloudflare Turnstile over Google reCAPTCHA
 * - AC2: Backend verification with Cloudflare API
 * - AC3: Challenge evaluation logic
 * - FR60: Graceful degradation (fail open)
 * - FR76: Bot protection with retry mechanism
 */

import type { TurnstileVerificationResult } from '../types';

/**
 * Cloudflare Turnstile API endpoint
 * Documentation: https://developers.cloudflare.com/turnstile/get-started/server-side-validation/
 */
const TURNSTILE_API_URL = 'https://challenges.cloudflare.com/turnstile/v0/siteverify';

/**
 * Verification timeout (3 seconds)
 * Matches reCAPTCHA timeout for consistency
 * If API doesn't respond within this time, fail open
 */
const VERIFICATION_TIMEOUT_MS = 3000;

/**
 * Verify Turnstile token with Cloudflare API
 *
 * Implements AC2: POST to Cloudflare API with secret key and token
 * Implements AC6: Fail-open pattern for network errors (don't block legitimate users)
 *
 * @param token - Token generated by Turnstile widget on frontend
 * @param secretKey - Turnstile secret key from environment (TURNSTILE_SECRET_KEY)
 * @returns Promise<TurnstileVerificationResult> - Verification result with success boolean
 *
 * @example
 * ```typescript
 * const result = await verifyTurnstileToken(token, env.TURNSTILE_SECRET_KEY);
 * if (result.success) {
 *   // User passed challenge
 * } else {
 *   // Bot detected or verification failed
 * }
 * ```
 */
export async function verifyTurnstileToken(
  token: string,
  secretKey: string
): Promise<TurnstileVerificationResult> {
  // Input validation
  if (!token || typeof token !== 'string') {
    console.warn('Turnstile token is missing or invalid. Failing open.');
    return {
      success: true, // Fail open: allow submission
      'error-codes': ['missing-input-response'],
    };
  }

  if (!secretKey || typeof secretKey !== 'string') {
    console.error('Turnstile secret key is missing. Failing open.');
    return {
      success: true, // Fail open: allow submission
      'error-codes': ['missing-input-secret'],
    };
  }

  try {
    // Create AbortController for timeout
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), VERIFICATION_TIMEOUT_MS);

    // POST to Cloudflare Turnstile API (AC2)
    const response = await fetch(TURNSTILE_API_URL, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        secret: secretKey,
        response: token,
      }),
      signal: controller.signal,
    });

    // Clear timeout
    clearTimeout(timeoutId);

    // Check HTTP status
    if (!response.ok) {
      console.error(`Turnstile API returned HTTP ${response.status}. Failing open.`);
      return {
        success: true, // Fail open: don't block users for API errors
        'error-codes': [`http-${response.status}`],
      };
    }

    // Parse JSON response (AC2: Parse response with success, challenge_ts, hostname, error-codes)
    const data = await response.json<TurnstileVerificationResult>();

    // Log verification result for monitoring (Task 9)
    if (data.success) {
      console.log('Turnstile verification successful', {
        challenge_ts: data.challenge_ts,
        hostname: data.hostname,
      });
    } else {
      console.warn('Turnstile challenge failed', {
        'error-codes': data['error-codes'] || [],
      });
    }

    return data;
  } catch (error) {
    // Network errors, timeouts, or API failures (AC6: Fail open)
    if (error instanceof Error) {
      if (error.name === 'AbortError') {
        console.warn('Turnstile verification timed out after 3s. Failing open.', {
          fail_open: true,
        });
      } else {
        console.error('Turnstile verification network error. Failing open.', {
          error: error.message,
          fail_open: true,
        });
      }
    } else {
      console.error('Turnstile verification unknown error. Failing open.', {
        fail_open: true,
      });
    }

    // Fail open: Allow submission (FR60 graceful degradation)
    return {
      success: true, // Don't block legitimate users for network issues
      'error-codes': ['network-error'],
    };
  }
}

/**
 * Evaluate Turnstile challenge result
 *
 * Implements AC3: Boolean evaluation (success === true passes, success === false rejects)
 * Simpler than reCAPTCHA's score-based evaluation (no threshold tuning needed)
 *
 * @param result - Turnstile verification result from verifyTurnstileToken()
 * @returns boolean - True if challenge passed (legitimate user), false if failed (likely bot)
 *
 * @example
 * ```typescript
 * const result = await verifyTurnstileToken(token, secretKey);
 * if (isChallengeSuccessful(result)) {
 *   // Allow submission
 * } else {
 *   // Reject as bot
 * }
 * ```
 */
export function isChallengeSuccessful(result: TurnstileVerificationResult): boolean {
  // AC3: Simple boolean check (no score threshold like reCAPTCHA)
  const passed = result.success === true;

  // Log evaluation for monitoring
  if (passed) {
    console.log('Turnstile challenge evaluation: PASSED');
  } else {
    console.warn('Turnstile challenge evaluation: FAILED', {
      'error-codes': result['error-codes'] || [],
    });
  }

  return passed;
}

/**
 * Convenience function: Verify and evaluate Turnstile in one call
 *
 * Combines verifyTurnstileToken() + isChallengeSuccessful() for simpler API endpoint usage
 * Mimics reCAPTCHA module pattern for consistency
 *
 * @param token - Turnstile token from frontend
 * @param secretKey - Secret key from environment
 * @returns Promise<{ passed: boolean; result: TurnstileVerificationResult }>
 *
 * @example
 * ```typescript
 * const { passed, result } = await verifyAndEvaluateTurnstile(token, env.TURNSTILE_SECRET_KEY);
 * if (!passed) {
 *   return c.json({ success: false, error: { code: 'BOT_DETECTED', message: 'Please try again' } }, 503);
 * }
 * ```
 */
export async function verifyAndEvaluateTurnstile(
  token: string,
  secretKey: string
): Promise<{ passed: boolean; result: TurnstileVerificationResult }> {
  const result = await verifyTurnstileToken(token, secretKey);
  const passed = isChallengeSuccessful(result);

  return { passed, result };
}
